apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-redis
  namespace: default
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: redis-service{{ .Release.Name }}
    protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
  type: {{ .Values.redis.service.type }}
