replicaCount: 1
nginx:
    image:
      repository: nginx
      tag: "1.25"
      pullPolicy: IfNotPresent
      port: 80
    service: 
      type: ClusterIP
      port: 80
      targetPort: 80
redis:
    image:
      repository: redis
      tag: latest
      pullPolicy: IfNotPresent
      port: 6379
    service: 
      type: ClusterIP
      port: 6379
      targetPort: 6379
postgres:
    image:
      repository: postgres
      tag: 13.22-trixie
      pullPolicy: IfNotPresent
      port: 8080
    service:
      type: ClusterIP
      port: 8080
      targetPort: 8080


